PLAT-1652: Move bastions to use spot instances
getndazn/terraform-aws-ssh-bastion-service pull request #3
Opened 2019-11-14 13:47 UTC by carvalho-dazn

2019-11-14 16:11 UTC, TomNorth submitted a review, later dismissed

2019-11-14 17:23 UTC, luis-silva requested changes

2019-11-14 17:23 UTC, luis-silva commented on main.tf
> +      on_demand_percentage_above_base_capacity = var.enviroment_name != "prod" ? 0 : 100
This should be zero because Rick wants Spot to be used in Prod as well.

2019-11-15 09:06 UTC, luis-silva approved these changes

2019-11-15 09:10 UTC, merged